export interface IFinalizarConsulta {
    comando: string,
    idPaciente: string,
    motivoConsulta: string,
    enfermedadActual: string,
    revisionPorSistemas: string,
    diagnostico: string,
    conducta: string,
    presionArterial: string,
    fc: string,
    fr: string,
    peso: string,
    talla: string,
    perimetroAbdominal: string,
    cabeza: string,
    cuello: string,
    torax: string,
    abdomen: string,
    extremidades: string,
    neurologico: string,
    osteomuscular: string,
    mental: string,
}
